# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  ecommerce:
    image: ecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5144:5144
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=db;Database=MyDb;User Id=sa;Password=Strong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Strong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"